tidy:
	go mod tidy
	go fmt ./src/...
	fieldalignment -fix ./src/...
	go vet ./src/...
	golangci-lint run --fix ./src/...
	staticcheck ./src/...

publish:
	@echo "Publishing to GitHub..."
	git add .
	git commit -m "Update"
	git push origin main
	git tag -a v0.0.19
	git push origin v0.0.19

