tidy:
	go mod tidy
	go fmt ./src/...
	fieldalignment -fix ./src/...
	go vet ./src/...
	golangci-lint run --fix ./src/...
	staticcheck ./src/...

publish:
	@echo "Publishing to GitHub..."
	git add .
	git commit -m "Update"
	git push origin main
	git tag -a v0.0.5-$(shell date +%Y%m%d%H%M%S) -m "Release $(shell date +%Y%m%d%H%M%S)"
	git push origin v$(shell date +%Y%m%d%H%M%S)
