package constant

var Animals = []string{
	"Aardvark", "Albatross", "Alligator", "Alpaca", "Ant", "Anteater", "Antelope",
	"Ape", "Armadillo", "Donkey", "Baboon", "Badger", "Barracuda", "Bat", "Bear",
	"Beaver", "Bee", "Bison", "Boar", "Buffalo", "Butterfly", "Camel", "Capybara",
	"Caribou", "Cassowary", "Cat", "Caterpillar", "Cattle", "Chamois", "Cheetah",
	"Chicken", "Chimpanzee", "Chinchilla", "Chough", "Clam", "Cobra", "Cockroach",
	"Cod", "Cormorant", "Coyote", "Crab", "Crane", "Crocodile", "Crow", "Curlew",
	"Deer", "Dinosaur", "Dog", "Dogfish", "Dolphin", "Dotterel", "Dove", "Dragonfly",
	"Duck", "Dugong", "Dunlin", "Eagle", "Echidna", "Eel", "Elephant", "Elk",
	"Emu", "Falcon", "Ferret", "Finch", "Fish", "Flamingo", "Fly", "Fox", "Frog",
	"Gaur", "Gazelle", "Gerbil", "Giraffe", "Gnat", "Gnu", "Goat", "Goldfinch",
	"Goldfish", "Goose", "Gorilla", "Goshawk", "Grasshopper", "Grouse", "Guan",
	"Gull", "Hamster", "Hare", "Hawk", "Hedgehog", "Heron", "Herring", "Hippopotamus",
	"Hornet", "Horse", "Human", "Hummingbird", "Hyena", "Ibex", "Ibis", "Jackal",
	"Jaguar", "Jay", "Jellyfish", "Kangaroo", "Kingfisher", "Koala", "Kookaburra",
	"Kouprey", "Kudu", "Lapwing", "Lark", "Lemur", "Leopard", "Lion", "Llama",
	"Lobster", "Locust", "Loris", "Louse", "Lyrebird", "Magpie", "Mallard", "Manatee",
	"Mandrill", "Mantis", "Marten", "Meerkat", "Mink", "Mole", "Mongoose", "Monkey",
	"Moose", "Mosquito", "Mouse", "Mule", "Narwhal", "Newt", "Nightingale", "Octopus",
	"Okapi", "Opossum", "Oryx", "Ostrich", "Otter", "Owl", "Oyster", "Panther",
	"Parrot", "Pony", "Porcupine", "Porpoise", "Quail", "Quelea", "Quetzal", "Rabbit",
	"Raccoon", "Rail", "Ram", "Rat", "Raven", "Red deer", "Red panda", "Reindeer",
	"Rhinoceros", "Rook", "Salamander", "Salmon", "Sand Dollar", "Sandpiper", "Sardine",
	"Scorpion", "Seahorse", "Seal", "Shark", "Sheep", "Shrew", "Skunk", "Snail",
	"Snake", "Sparrow", "Spider", "Spoonbill", "Squid", "Squirrel", "Starling",
	"Stingray", "Stinkbug", "Stork", "Swallow", "Swan", "Tapir", "Tarsier", "Termite",
	"Tiger", "Toad", "Trout", "Turkey", "Turtle", "Viper", "Vulture", "Wallaby",
	"Walrus", "Wasp", "Weasel", "Whale", "Wildcat", "Wolf", "Wolverine", "Wombat",
	"Woodcock", "Woodpecker", "Worm", "Wren", "Yak", "Zebra",
}

var Adjectives = []string{
	"Adorable", "Bouncy", "Cheeky", "Chubby", "Clumsy", "Cuddly", "Curious", "Dainty", "Dapper",
	"Delightful", "Dizzy", "Dreamy", "Droopy", "Fluffy", "Fuzzy", "Giggly", "Goofy", "Grumpy", "Happy",
	"Hungry", "Itchy", "Jolly", "Kooky", "Lazy", "Lively", "Loopy", "Lovely", "Lumpy",
	"Merry", "Mischievous", "Mushy", "Nifty", "Nimble", "Nutty", "Peppy", "Perky", "Playful", "Plump",
	"Poofy", "Proud", "Puffy", "Quirky", "Sassy", "Scaly", "Scruffy", "Shaggy", "Shiny", "Silly",
	"Slippery", "Smelly", "Snappy", "Snugly", "Squeaky", "Squishy", "Stealthy", "Stubby", "Sunny",
	"Tiny", "Toothy", "Tricky", "Wacky", "Wiggly", "Wimpy", "Zany", "Zippy", "Bubbly", "Chirpy",
	"Drowsy", "Eager", "Feisty", "Gleeful", "Huggable", "Inky", "Jumpy",
	"Kooky", "Luminous", "Mirthful", "Nosey", "Peachy", "Perky", "Piquant", "Plucky", "Poised", "Pudgy",
	"Quacky", "Raspy", "Roasty", "Squeaky", "Swirly", "Ticklish", "Twirly", "Whiskery", "Wobbly", "Zesty",
	"Dumb",
}

var Verbs = []string{
	"Adventuring", "Ambling", "Bouncing", "Bumbling", "Burrowing", "Buzzing", "Cackling", "Camping",
	"Chasing", "Chirping", "Climbing", "Clucking", "Crawling", "Dancing", "Darting", "Digging",
	"Dodging", "Dozing", "Dribbling", "Drumming", "Ducking", "Flapping", "Flickering", "Fluttering",
	"Frolicking", "Galloping", "Giggling", "Gliding", "Grazing", "Grinning", "Growling", "Hopping",
	"Hunting", "Hustling", "Jiggling", "Jogging", "Jumping", "Kicking", "Kissing", "Knocking",
	"Lapping", "Leaping", "Licking", "Loafing", "Lolling", "Lurking", "Mimicking", "Mouthing",
	"Napping", "Nibbling", "Nuzzling", "Paddling", "Pacing", "Pecking", "Pouncing", "Prancing",
	"Purring", "Racing", "Rattling", "Roaring", "Rolling", "Rumbling", "Scampering", "Scurrying",
	"Shaking", "Shrieking", "Skipping", "Slithering", "Sloshing", "Smiling", "Snapping", "Sniffing",
	"Snoring", "Snuggling", "Soaring", "Spinning", "Splashing", "Squawking", "Squeaking", "Squealing",
	"Sprinting", "Squirming", "Stomping", "Strutting", "Strolling", "Stuttering", "Swimming", "Tapping",
	"Twitching", "Waddling", "Wagging", "Wandering", "Winking", "Wrestling", "Yawning", "Zooming",
	"Awakening", "Babbling", "Balancing", "Barking", "Basking", "Beaming", "Beating", "Blowing",
	"Bobbing", "Booping", "Bouncing", "Bowing", "Breathing", "Bristling", "Brooding", "Bubbling",
	"Buzzing", "Calming", "Carrying", "Cawing", "Chattering", "Chewing", "Chilling", "Chirping",
	"Chomping", "Clambering", "Clapping", "Clawing", "Climbing", "Clucking", "Coiling", "Comforting",
	"Composing", "Concealing", "Confiding", "Cooing", "Crawling", "Cresting", "Croaking", "Crackling",
	"Cuddling", "Dazzling", "Diving", "Dodging", "Drifting", "Drumming", "Ducking", "Dusting",
	"Eating", "Echoing", "Eluding", "Emerging", "Exploring", "Flashing", "Flapping", "Flicking",
	"Flipping", "Floating", "Fooling", "Foraging", "Frowning", "Galloping", "Glistening", "Glowing",
	"Gliding", "Grinning", "Grooving", "Gurgling", "Hopping", "Hugging", "Hunting", "Hiding",
}
